### ISSUE TITLE
Carl-bot message maker

### ISSUE THREAD

**Issue by coxender** [EMU-Compsci-Discord/CompsciBot#33]
Making the carlbot message is now the hardest part of making semester channels, besides getting the csv.  It would be nice to have CompSciBot improve the message making experience for consistency between semesters, and general ease.

A few options worth looking into include:
|Option| Description |
| ----------- | ----------- |
| CompSciBot calls Carl-bot and arranges the channels itself (optional feature)|- This could be difficult, as it would require the bots to interact, which may not be possible with the way CompSciBot and/or Carl-bot is setup.<br> - Specifically, CompSciBot may be programmed to not respond to bots. This could make interaction impossible unless it is a one-time bot call. |
|  CompSciBot prints out premade lists for an Admin to setup channels (automatically done)| - CompSciBot prints out a premade list of emojis and roles, as well as a premade message to hand to Carl-bot for the admin to use.<br>- If this is done, it would be nice to have the command to use also printed.|

**Comment by Nanosplitter** [comment]
Carl-bot definitely doesn't allow messages from bots, and we don't want to risk allowing bots to execute commands on compsci bot, so I think option 2 is probably best
