### ISSUE TITLE
Create Math and Electives Category

### ISSUE THREAD

**Issue by nstringham** [EMU-Compsci-Discord/CompsciBot#45]
Any class 400-500 (edge case 481,321) be in electives category
Any class starting with MATH or STATS be in math electives category
Delete 500 level with corresponding 400 level classes (or combine to one category)

**Comment by nstringham** [comment]
Do we really want this? it seems to me like it would be better to have each course number have its own category.

**Comment by coxender** [comment]
I have no preference, it's small enough (2 classes I think) that it could be in its own category.

**Comment by nstringham** [comment]
> I have no preference, it's small enough (2 classes I think) that it could be in its own category.

This semester it's 6 not 2
![image](https://user-images.githubusercontent.com/44071655/192000969-95cb1056-6036-48be-847f-e16425027d4a.png)

**Comment by nstringham** [comment]
Unless you mean CompSci classes in which case there are also more than 2
![image](https://user-images.githubusercontent.com/44071655/192001427-6c2f64c8-83cd-40f5-8d81-a5ee89ce3355.png)

**Comment by coxender** [comment]
Sorry I meant to say courses, as there is only math120 and stat360.  

The amount of categories is only 2 was my point, one more than if it was grouped in a math and stats section.  Not enough for me to argue against keeping them separate.

**Comment by nstringham** [comment]
I see

**Comment by nstringham** [comment]
What about the electives?

**Comment by coxender** [comment]
Sorry I'm in mobile and accidentally hit edit yours.

**Comment by coxender** [comment]
Eh... An electives group would keep us from needing two messages to send reaction roles, but also i can see the problem with having to mute them.

**Comment by nstringham** [comment]
And having to explain to users where there class is

**Comment by coxender** [comment]
Seems like more downsides then.  I will close this.
