### ISSUE TITLE
remove /poll in favor of Carl-bot

### ISSUE THREAD

**Issue by nstringham** [EMU-Compsci-Discord/CompsciBot#49]
carl bot has a poll command that is better than ours so instead of improving our poll command we should remove it and make sure that users have permission to use the carl bot poll command on the server

https://docs.carl.gg/utilities/info-polls/#polls

**Comment by nstringham** [comment]
this would solve #48

**Comment by nstringham** [comment]
if we go with carl bot polls we should cancel #42

**Comment by coxender** [comment]
I think that is a good idea, we don't need a replica command.
